- name:  install and start nginx
  hosts: local
  become: yes
  tasks:
   - name:  install nginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name: start nginx
     server:
      name: nginx
      state: present
      enabled: yes
      





