- name:  install and start nginx
  hosts: local
  become: true
  tasks:
   - name:  install nginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name: start nginx service
     ansible.builtin.package:
      name: nginx
      state: started
      enabled: true
      





