- name: Install and start Nginx
  hosts: localhost
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

# ; local group vars
# ; [local:vars]
# ; COURSE="Ansible"
# ; TRAINER="Sivakumar"
# ; DURATION="10HRS"

# ; [frontend:vars]
# ; COURSE="Ansible"
# ; TRAINER="Sivakumar"
# ; DURATION="10HRS"
