---
- name: "Demo Playbook"
  hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars_files:
    - course.yaml

  tasks:
    - name: "course details"
      ansible.builtin.debug:
        msg: "{{ course }} by {{ trainer }}, is {{ duration }}"
        



    
    

  


    

  
      
    


