- name: demo play criecket
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - player.yaml
  
  tasks:
  - name: criecket
    ansible.builtin.debug:
      msg: "{{country}} by {{captain}} is {{player}}"


    

