- name: demo on inventory
  hosts: frontend
  # connection: local
  gather_facts: false
  tasks:
    - name: print name
      debug:
        msg: "Hi, I am learning  is {{ trainer }}, Duration is {{ duration }}"
        
        
        
        
  


