- name: demo on inventory
  hosts: frontend
  gather_facts: false

  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "Hi, I am learning, trainer is {{ trainer }}, Duration is {{ duration }}"
        

        
        
        
        
  


