- name: demo on inventory variable
  hosts: frontend
  # connection: local
  gather_facts: false
  
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "Hi, I am learning  is {{ trainer }}, Duration is {{ duration }},{{common_key}}"
      
        
        
        

        
        
        
        
  


