- name: check the variable data type
  hosts: local
  connection: local
  vars:
    course: "python with AIops"
    duration: "150HRS"
    is_live_sessions: true
    tops:
    - linux
    - shell
    - ansible
    more_details:
      month: "5"
      trainer: "manikuamr"
      msg: |
        name: {{course}}
        duration: {{duration}}
        is_it_live_: {{is_live_sessions}}
        tops: {{tops}}
        

      
    


