- name: check the variable live_sessions
  hosts: local
  
  vars:
  is_it_live: 4
  tasks:
  - name: more than 5 sessions
    ansible.builtin.debug:
      msg: "yes,ansible took the sessions 5"
      when: live_sessions >5


      

  
 
