- name: Demo on loop
  hosts: local
  connection: local
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
    - manikuamr
    - siva
    - prasadhu
     



    
    


