- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: "Linux, Ansible, Terraform, Git"
    topmap:
    name: Ansible
    project: roboshop
    environment: dev
    
  
    taglist:
      - { key: "name", value: "Ansible" }
      - { key: "project", value: "roboshop" }
      - { key: "environment", value: "dev" }
 

    
  tasks:
  - name: Convert string to list
    debug:
      msg: "{{ topics | split(',') }}"

  
  - name: default value if variable not defined
    debug:
      msg: "{{ Greeting | default('Good Moring') }}"

  - name: Convert map to list
    ansible.builtin.debug:
      msg: "{{ tagmap | dict2items }}"
    
 
  
      
    
    
  
  

  
      
   
    

  
 
      

  


