- name: demo on filters
  hosts: local
  connection: local
  vars:
    topices: "Linux, ansible,docker, git"
  tasks: 
  - name: convert to strong List
    ansible.builtin.debug:
      msg: " Topices: {{topices | split(',')}}"

  - name: default value for variable
    ansible.builtin.debug:
      msg: "{{Greeting |default(GoodMorning)}}"
