- name: demo on shell vs command
  hosts: local
  connection: local
  tasks:
  - name: shell test
    shell: cat /etc/passwd | grep root
    register: user_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{user_output}}"

     
  
  
  
   
    
