- name : demo on Error Handling
  hosts: local
  connection: local
  
  tasks: 
  - name: check if roboshop user exists
    command: id roboshop
    register: user_output
    ignore_errors: yes

  - name: print user_output
    debug:
      msg:  "{{user_output}}"

  - name: create user
    command: useradd roboshop
    when: user_output.rc != 0 

    
    
  
