[frontend]
172.31.31.10 course= "Ansible for Node-1"
172.31.29.10 course= "Ansible for Node-2"


 [user]
 172.31.27.131



 [cart]
 172.31.27.132

# group of group children
; [roboshop:children]
; frontend
; catalogue
; user
; cart




[local]
localhost

#local group vars
[local:vars]
course= "DevOpsecops of AWS"
trainer= "manikumar"
duration= "150HR"

[frontend:vars]
course= "DevOpsecops of AWS"
trainer= "manikumar"
duration= "150HR"



